<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.apache.derby</groupId>
        <artifactId>derby-project</artifactId>
        <version>10.16.1.2-talend-20260121</version>
    </parent>

    <artifactId>ant-build</artifactId>
    <packaging>pom</packaging>

    <description>Use it just to automate the run of the ant tasks in advance</description>

    <build>
        <plugins>
            <plugin>
                <artifactId>maven-antrun-plugin</artifactId>
                <executions>
                    <execution>
                        <phase>generate-sources</phase>
                        <configuration>
                            <target>
                                <property name="sane" value="${sane.value}"/>
<!--                                <ant antfile="${project.basedir}/../../build.xml"-->
<!--                                     target="clobber"-->
<!--                                     dir="${project.basedir}/../.."-->
<!--                                     inheritAll="true"/>-->
<!--                                <ant antfile="${project.basedir}/../../build.xml"-->
<!--                                     target="buildsource"-->
<!--                                     dir="${project.basedir}/../.."-->
<!--                                     inheritAll="true"/>-->
                                <ant antfile="${project.basedir}/../../build.xml"
                                     target="buildjars"
                                     dir="${project.basedir}/../.."
                                     inheritAll="true"/>
                            </target>
                        </configuration>
                        <goals>
                            <goal>run</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>